<?php
/*
Plugin Name: Vue Chatbot Integration
Description: Intègre un chatbot Vue.js dans WordPress.
Version: 1.0
Author: Loïc Chazeau
*/

// Enqueue Vue.js App Scripts and Styles
function enqueue_vue_chatbot_scripts() {
    // Enqueue the CSS file generated by Vite
    wp_enqueue_style('vue-chatbot-style', plugin_dir_url(__FILE__) . 'dist/assets/index.css');

    // Enqueue the JS file generated by Vite
    wp_enqueue_script('vue-chatbot-script', plugin_dir_url(__FILE__) . 'dist/assets/index.js', array(), null, true);
}
add_action('wp_enqueue_scripts', 'enqueue_vue_chatbot_scripts');

// Shortcode to Display the Vue.js App
function display_vue_chatbot() {
    return '<div id="app"></div>';
}
add_shortcode('vue_chatbot', 'display_vue_chatbot');
